const NAV=[['dashboard','🏰 Accueil'],['quests','📜 Quêtes'],['character','👤 Personnage'],['world','🗺️ Ylinor'],['shop','💰 Boutique'],['achievements','🏆 Succès'],['calendar','📅 Calendrier'],['journal','📖 Journal']];
const STATS={power:['⚔️','Puissance'],resistance:['🛡️','Résistance'],endurance:['🏃','Endurance'],knowledge:['🧠','Savoir'],creation:['🎨','Création'],discipline:['⚖️','Discipline'],influence:['💬','Influence'],vitality:['🌿','Vitalité'],soul:['✨','Âme'],wisdom:['👁️','Sagesse']};
const REGIONS=[
{id:'forge',name:'Forge éthérienne',icon:'⚒️',desc:'Travaux, maison et fabrication.',unlock:1},
{id:'academy',name:'Académie des Érudits',icon:'🏛️',desc:'Cours, transmission et savoir.',unlock:2},
{id:'guild',name:'Guilde Bénathor',icon:'⚔️',desc:'Effort, santé et dépassement.',unlock:3},
{id:'archives',name:'Archives d’Ylinor',icon:'📚',desc:'JDR, écriture et imagination.',unlock:5},
{id:'sanctuary',name:'Sanctuaire de Vinraës',icon:'🌿',desc:'Repos, soin et équilibre.',unlock:7},
{id:'senacle',name:'Le Sénacle',icon:'🔱',desc:'Décisions majeures et quêtes épiques.',unlock:10}
];
const SHOP=[
{id:'avatar_knight',name:'Armure du Vagabond',icon:'🦹',cost:120,currency:'soul',type:'avatar'},
{id:'avatar_mage',name:'Voile de l’Astromancien',icon:'🧙‍♂️',cost:160,currency:'soul',type:'avatar'},
{id:'title_builder',name:'Titre : Façonneur',icon:'🪨',cost:90,currency:'soul',type:'title',value:'Le Façonneur de Pierre'},
{id:'title_sage',name:'Titre : Érudit',icon:'📜',cost:110,currency:'soul',type:'title',value:'L’Érudit d’Ylinor'},
{id:'theme_copper',name:'Sceau de cuivre',icon:'🟠',cost:70,currency:'gold',type:'cosmetic'},
{id:'companion_raven',name:'Corbeau compagnon',icon:'🐦‍⬛',cost:240,currency:'soul',type:'cosmetic'}
];
const ACHIEVEMENTS=[
{id:'first',name:'Premier pas',icon:'🔥',desc:'Terminer une première quête.',test:s=>s.completed>=1},
{id:'ten',name:'Aventurier',icon:'🗡️',desc:'Terminer 10 quêtes.',test:s=>s.completed>=10},
{id:'level5',name:'Ascension',icon:'⬆️',desc:'Atteindre le niveau 5.',test:s=>s.level>=5},
{id:'streak7',name:'Sept flammes',icon:'🕯️',desc:'Maintenir une série de 7 jours.',test:s=>s.streak>=7},
{id:'rich',name:'Moissonneur d’âmes',icon:'💠',desc:'Posséder 500 fragments.',test:s=>s.souls>=500},
{id:'world',name:'Explorateur',icon:'🗺️',desc:'Débloquer 4 régions.',test:s=>REGIONS.filter(r=>s.level>=r.unlock).length>=4}
];
const DEFAULT={
 version:1,name:'Pierre',title:'Le Novice',avatar:'🧙',xp:0,level:1,rank:'F',souls:0,gold:0,streak:0,lastActive:null,completed:0,
 stats:Object.fromEntries(Object.keys(STATS).map(k=>[k,0])),owned:[],unlockedAchievements:[],activity:{},
 quests:[
  {id:crypto.randomUUID(),title:'Façonner la Grotte',description:'Avancer le crépi ou les finitions de la salle de bain.',type:'weekly',difficulty:4,stat:'creation',xp:180,done:false},
  {id:crypto.randomUUID(),title:'Le Souffle des Anciens',description:'Faire 20 minutes de vélo elliptique.',type:'daily',difficulty:2,stat:'endurance',xp:60,done:false},
  {id:crypto.randomUUID(),title:'Former les Apprentis',description:'Préparer ou améliorer un cours.',type:'weekly',difficulty:3,stat:'knowledge',xp:90,done:false},
  {id:crypto.randomUUID(),title:'Chroniques d’Ylinor',description:'Faire avancer le JDR ou créer un élément de lore.',type:'epic',difficulty:5,stat:'creation',xp:260,done:false}
 ],
 journal:[{id:crypto.randomUUID(),date:new Date().toISOString(),title:'Le commencement',text:'L’Ascendant a franchi le seuil. Ylinor attend désormais chacune de ses victoires.'}]
};
let state=load();let activeQuestTab='all';let calendarCursor=new Date();let selectedAvatar=state.avatar;
function load(){try{return {...structuredClone(DEFAULT),...JSON.parse(localStorage.getItem('ascensionYlinor')||'{}')}}catch{return structuredClone(DEFAULT)}}
function save(){localStorage.setItem('ascensionYlinor',JSON.stringify(state));renderAll()}
function xpForLevel(l){return 100+Math.floor((l-1)*55+Math.pow(l-1,1.35)*18)}
function updateLevel(){while(state.xp>=xpForLevel(state.level)){state.xp-=xpForLevel(state.level);state.level++;state.gold+=20;state.souls+=50;toast(`Niveau ${state.level} atteint !`)}state.rank=state.level>=30?'S':state.level>=22?'A':state.level>=15?'B':state.level>=10?'C':state.level>=6?'D':state.level>=3?'E':'F'}
function touchActivity(){const d=new Date().toISOString().slice(0,10);if(state.lastActive!==d){const y=new Date();y.setDate(y.getDate()-1);const yd=y.toISOString().slice(0,10);state.streak=state.lastActive===yd?state.streak+1:1;state.lastActive=d}state.activity[d]=(state.activity[d]||0)+1}
function completeQuest(id){const q=state.quests.find(x=>x.id===id);if(!q||q.done)return;q.done=true;state.xp+=q.xp;state.souls+=Math.round(q.xp*.6);state.gold+=Math.max(5,q.difficulty*3);state.stats[q.stat]=(state.stats[q.stat]||0)+q.difficulty*8;state.completed++;touchActivity();state.journal.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),title:`Quête accomplie : ${q.title}`,text:`L’Ascendant a triomphé de « ${q.title} ». +${q.xp} XP et la vertu ${STATS[q.stat][1]} s’est renforcée.`});updateLevel();checkAchievements();save();toast(`Quête accomplie : +${q.xp} XP`)}
function checkAchievements(){ACHIEVEMENTS.forEach(a=>{if(!state.unlockedAchievements.includes(a.id)&&a.test(state)){state.unlockedAchievements.push(a.id);state.souls+=75;toast(`Trophée débloqué : ${a.name}`)}})}
function navTo(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id+'View').classList.add('active');document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));window.scrollTo({top:0,behavior:'smooth'})}
function renderNav(){document.getElementById('nav').innerHTML=NAV.map(([id,label])=>`<button data-nav="${id}" class="${id==='dashboard'?'active':''}">${label}</button>`).join('')}
function renderHeader(){['topName','characterName','profileName'].forEach(id=>document.getElementById(id).textContent=state.name);['topTitle','characterTitle','profileTitle'].forEach(id=>document.getElementById(id).textContent=state.title);document.getElementById('topLevel').textContent=state.level;document.getElementById('rankLabel').textContent=state.rank;const next=xpForLevel(state.level);document.getElementById('xpLabel').textContent=state.xp;document.getElementById('xpNextLabel').textContent=next;document.getElementById('xpBar').style.width=`${Math.min(100,state.xp/next*100)}%`;document.getElementById('soulCount').textContent=state.souls;document.getElementById('goldCount').textContent=state.gold;document.getElementById('streakCount').textContent=state.streak;['avatarPreview','avatarLarge'].forEach(id=>document.getElementById(id).textContent=state.avatar)}
function questHTML(q){return `<article class="quest-card ${q.done?'done':''}"><div><h3>${escapeHtml(q.title)}</h3><p>${escapeHtml(q.description||'')}</p><div class="quest-meta">${labelType(q.type)} · ${'★'.repeat(q.difficulty)} · ${STATS[q.stat][0]} ${STATS[q.stat][1]}</div><div class="quest-reward">+${q.xp} XP · +${Math.round(q.xp*.6)} fragments</div></div><div class="quest-actions">${q.done?'<span>Accomplie</span>':`<button class="check" data-complete="${q.id}" title="Terminer">✓</button>`}<button class="ghost small" data-delete="${q.id}">🗑</button></div></article>`}
function renderDashboard(){const active=state.quests.find(q=>!q.done)||state.quests[0];document.getElementById('featuredQuest').innerHTML=active?`<h2>${escapeHtml(active.title)}</h2><p>${escapeHtml(active.description)}</p><p class="quest-reward">${'★'.repeat(active.difficulty)} · +${active.xp} XP</p>${active.done?'':`<button class="primary" data-complete="${active.id}">Accomplir</button>`}`:'<p>Aucune quête active.</p>';document.getElementById('dailyQuestList').innerHTML=state.quests.filter(q=>q.type==='daily').slice(0,4).map(questHTML).join('')||'<p>Aucune quête quotidienne.</p>';document.getElementById('statMiniGrid').innerHTML=Object.entries(STATS).slice(0,6).map(([k,[i,n]])=>`<div class="stat-chip">${i} ${n}<b>${state.stats[k]}</b></div>`).join('');document.getElementById('worldMini').innerHTML=`<div class="region-mini">${REGIONS.slice(0,4).map(r=>`<div class="region-line"><span>${r.icon} ${r.name}</span><b>${state.level>=r.unlock?'Débloquée':`Niv. ${r.unlock}`}</b></div>`).join('')}</div>`;const j=state.journal[0];document.getElementById('recentJournal').innerHTML=j?`<b>${escapeHtml(j.title)}</b><p>${escapeHtml(j.text)}</p>`:'<p>Aucune chronique.</p>'}
function renderQuests(){document.getElementById('questTabs').innerHTML=[['all','Toutes'],['daily','Quotidiennes'],['weekly','Hebdomadaires'],['epic','Épiques'],['done','Accomplies']].map(([id,l])=>`<button data-qtab="${id}" class="${activeQuestTab===id?'active':''}">${l}</button>`).join('');let qs=state.quests;if(activeQuestTab==='done')qs=qs.filter(q=>q.done);else if(activeQuestTab!=='all')qs=qs.filter(q=>q.type===activeQuestTab);document.getElementById('questBoard').innerHTML=qs.map(questHTML).join('')||'<div class="panel">Aucune quête ici.</div>'}
function renderCharacter(){document.getElementById('statsGrid').innerHTML=Object.entries(STATS).map(([k,[i,n]])=>{const v=state.stats[k]||0;const lvl=Math.floor(v/100)+1;return `<div class="stat-card"><div class="xp-line"><span>${i} ${n}</span><b>Niv. ${lvl}</b></div><div class="progress"><i style="width:${v%100}%"></i></div><small>${v%100} / 100</small></div>`}).join('')}
function renderWorld(){const unlocked=REGIONS.filter(r=>state.level>=r.unlock).length;document.getElementById('worldProgressText').textContent=`${unlocked}/${REGIONS.length} régions découvertes`;document.getElementById('worldMap').innerHTML=REGIONS.map(r=>`<article class="region-card ${state.level<r.unlock?'locked':''}"><span class="region-level">${state.level>=r.unlock?'Accessible':`Niveau ${r.unlock}`}</span><div class="region-icon">${r.icon}</div><h3>${r.name}</h3><p>${r.desc}</p><small>${state.level>=r.unlock?'La région répond à ton influence.':'Encore plongée dans le brouillard.'}</small></article>`).join('')}
function renderShop(){document.getElementById('shopSoulCount').textContent=state.souls;document.getElementById('shopGoldCount').textContent=state.gold;document.getElementById('shopGrid').innerHTML=SHOP.map(i=>{const owned=state.owned.includes(i.id);return `<article class="shop-item ${owned?'owned':''}"><div class="shop-icon">${i.icon}</div><h3>${i.name}</h3><p>${owned?'Possédé':`${i.currency==='soul'?'💠':'🪙'} ${i.cost}`}</p><button class="${owned?'ghost':'primary'}" ${owned?'disabled':''} data-buy="${i.id}">${owned?'Acquis':'Acheter'}</button></article>`}).join('')}
function buyItem(id){const i=SHOP.find(x=>x.id===id);if(!i||state.owned.includes(id))return;const key=i.currency==='soul'?'souls':'gold';if(state[key]<i.cost){toast('Ressources insuffisantes');return}state[key]-=i.cost;state.owned.push(id);if(i.type==='avatar')state.avatar=i.icon;if(i.type==='title')state.title=i.value;save();toast(`${i.name} acquis`)}
function renderAchievements(){document.getElementById('achievementCount').textContent=`${state.unlockedAchievements.length}/${ACHIEVEMENTS.length} débloqués`;document.getElementById('achievementGrid').innerHTML=ACHIEVEMENTS.map(a=>{const u=state.unlockedAchievements.includes(a.id);return `<article class="achievement ${u?'unlocked':''}"><div class="achievement-icon">${u?a.icon:'🔒'}</div><h3>${a.name}</h3><p>${a.desc}</p><small>${u?'Débloqué · +75 fragments':'Non débloqué'}</small></article>`}).join('')}
function renderCalendar(){document.getElementById('calendarStreak').textContent=state.streak;document.getElementById('calendarTitle').textContent=calendarCursor.toLocaleDateString('fr-FR',{month:'long',year:'numeric'});const first=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth(),1),start=new Date(first);start.setDate(start.getDate()-((first.getDay()+6)%7));let html=['L','M','M','J','V','S','D'].map(x=>`<div class="calendar-cell"><b>${x}</b></div>`).join('');for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const key=d.toISOString().slice(0,10);const same=d.getMonth()===calendarCursor.getMonth(),today=key===new Date().toISOString().slice(0,10),active=state.activity[key];html+=`<div class="calendar-cell ${same?'':'muted'} ${active?'active-day':''} ${today?'today':''}"><b>${d.getDate()}</b>${active?`<div>⚔️ ${active}</div>`:''}</div>`}document.getElementById('calendarGrid').innerHTML=html;document.getElementById('streakRewards').innerHTML=[[3,'30 fragments'],[7,'Coffre rare'],[30,'Titre exclusif'],[100,'Trophée légendaire']].map(([n,r])=>`<div class="reward-line"><b>${n} jours</b><span style="float:right">${state.streak>=n?'✅':'🔒'} ${r}</span></div>`).join('')}
function renderJournal(){document.getElementById('journalList').innerHTML=state.journal.map(j=>`<article class="journal-entry"><time>${new Date(j.date).toLocaleString('fr-FR')}</time><h3>${escapeHtml(j.title)}</h3><p>${escapeHtml(j.text)}</p></article>`).join('')}
function renderAll(){renderHeader();renderDashboard();renderQuests();renderCharacter();renderWorld();renderShop();renderAchievements();renderCalendar();renderJournal()}
function labelType(t){return t==='daily'?'Quotidienne':t==='weekly'?'Hebdomadaire':'Épique'}
function escapeHtml(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function toast(msg){const t=document.getElementById('toast');t.textContent=msg;t.classList.add('show');clearTimeout(t._x);t._x=setTimeout(()=>t.classList.remove('show'),2500)}
function openQuest(){document.getElementById('questForm').reset();document.getElementById('questDialog').showModal()}
function openAvatar(){const f=document.getElementById('avatarForm');f.name.value=state.name;f.title.value=state.title;selectedAvatar=state.avatar;renderAvatarChoices();document.getElementById('avatarDialog').showModal()}
function renderAvatarChoices(){const arr=['🧙','🧝','🧛','🦹','🧑‍🚀','🧑‍🎨','🧑‍🏫','🧑‍🔧','🥷','🧙‍♂️','🗿','🐦‍⬛'];document.getElementById('avatarChoices').innerHTML=arr.map(a=>`<button type="button" class="avatar-choice ${a===selectedAvatar?'selected':''}" data-avatar="${a}">${a}</button>`).join('')}
function initForms(){document.getElementById('questStatSelect').innerHTML=Object.entries(STATS).map(([k,[i,n]])=>`<option value="${k}">${i} ${n}</option>`).join('');document.getElementById('questForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.quests.unshift({id:crypto.randomUUID(),title:f.get('title'),description:f.get('description'),type:f.get('type'),difficulty:+f.get('difficulty'),stat:f.get('stat'),xp:+f.get('xp'),done:false});document.getElementById('questDialog').close();save();toast('Quête ajoutée')});document.getElementById('avatarForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.name=f.get('name')||state.name;state.title=f.get('title')||state.title;state.avatar=selectedAvatar;document.getElementById('avatarDialog').close();save()});document.getElementById('journalForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target);state.journal.unshift({id:crypto.randomUUID(),date:new Date().toISOString(),title:f.get('title'),text:f.get('text')});document.getElementById('journalDialog').close();e.target.reset();save()})}
document.addEventListener('click',e=>{const n=e.target.closest('[data-nav]');if(n)navTo(n.dataset.nav);const a=e.target.closest('[data-action]');if(a){if(a.dataset.action==='new-quest')openQuest();if(a.dataset.action==='open-avatar')openAvatar();if(a.dataset.action==='add-journal')document.getElementById('journalDialog').showModal();if(a.dataset.action==='prev-month'){calendarCursor.setMonth(calendarCursor.getMonth()-1);renderCalendar()}if(a.dataset.action==='next-month'){calendarCursor.setMonth(calendarCursor.getMonth()+1);renderCalendar()}}const c=e.target.closest('[data-complete]');if(c)completeQuest(c.dataset.complete);const d=e.target.closest('[data-delete]');if(d&&confirm('Supprimer cette quête ?')){state.quests=state.quests.filter(q=>q.id!==d.dataset.delete);save()}const t=e.target.closest('[data-qtab]');if(t){activeQuestTab=t.dataset.qtab;renderQuests()}const b=e.target.closest('[data-buy]');if(b)buyItem(b.dataset.buy);const av=e.target.closest('[data-avatar]');if(av){selectedAvatar=av.dataset.avatar;renderAvatarChoices()}});
renderNav();initForms();checkAchievements();renderAll();
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
